# Generated by Django 2.0.5 on 2018-05-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(0, 'Non evento'), (1, 'Apertura'), (2, 'Continuazione'), (3, 'Chiusura')])),
                ('stamp', models.DateTimeField()),
                ('stamp_evento', models.DateTimeField(blank=True, null=True)),
                ('linea', models.CharField(blank=True, max_length=50, null=True)),
                ('causa', models.CharField(blank=True, max_length=100, null=True)),
                ('testo', models.CharField(max_length=250)),
                ('root_tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweet.Tweet')),
            ],
            options={
                'verbose_name_plural': 'Tweet rilevati dallo stream di ATM',
            },
        ),
    ]
